### ISSUE TITLE
Validation Context 

### ISSUE THREAD

**Issue by Sathish9222** [DevExpress-Examples/XAF_how-to-enforce-password-complexity-in-xaf-e2849#1]
<Action Id="DialogOK" ValidationContexts="ChangePassword" />

Valisation Context is not available in the latest 19.1.7 version. Kindly let us know how we can proceed

**Comment by dennis-garavsky** [comment]
The ValidationContexts property is available in the Model Editor under ActionDesign | Actions | YourAction.
To research your situation, please attach your sample and screenshots showing what you tried to a new ticket in the DevExpress Support Center: https://www.devexpress.com/ask. With that, we will be able to assist you further.
